# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $redisHost: '%env(REDIS_HOST)%'


    _instanceof:
        App\Lib\CQRS\QueryHandlerInterface:
            tags: ['cqrs.query_handler']
        App\Lib\CQRS\CommandHandlerInterface:
            tags: ['cqrs.command_handler']

        App\Lib\Sms\Service\Provider\SmsProviderInterface:
            tags: ['sms.provider']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Auth\Repository\AccessTokenRepository:
        $accessTokenLifeTime: '%env(ACCESS_TOKEN_LIFETIME)%'

    App\Auth\Repository\BannedEmailRepository:
        $phoneBanTime: '%env(BAN_PHONE_TIME)%'

    App\Auth\Repository\ConfirmationTokenRepository:
        $confirmationTokenLifeTime: '%env(CONFIRMATION_TOKEN_LIFETIME)%'

    App\Auth\Repository\ConfirmationTimeoutRepository:
        $timeout: '%env(CONFIRM_SMS_TIMEOUT)%'


    App\Lib\CQRS\MessageHandler\AsyncCommandMessageHandler:
        $commandHandlers: !tagged_iterator 'cqrs.command_handler'

    App\Lib\CQRS\MessageHandler\CommandMessageHandler:
        $commandHandlers: !tagged_iterator 'cqrs.command_handler'

    App\Lib\CQRS\MessageHandler\QueryMessageHandler:
        $queryHandlers: !tagged_iterator 'cqrs.query_handler'

    App\Lib\Sms\Service\Provider\SmsProviderFactory:
        $provider: '%env(SMS_PROVIDER)%'
        $providers: !tagged_iterator 'sms.provider'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
